name: Simple npm audit

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install
      - name: Run npm audit
        run: npm audit --audit-level=moderate
